services:
  usermanagement:
    image: kishorejetty2023/usermanagement:1.0.0
    container_name: usermanagement
    ports:
      - "9091:9091"
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MY_SQL_URL=mysql
      - JAVA_OPTS=-Xms512m -Xmx1024m -Dlogging.level.root=DEBUG
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin@1234
      MYSQL_DATABASE: myspringapps
      MYSQL_USER: spring
      MYSQL_PASSWORD: Admin@1234
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
