management:
  endpoints:
    web:
      base-path: /manage
  server:
    port: 8083
org:
  springframework:
    data:
      jpa:
        repository:
          level: FINE
logging:
  level:
    org.hibernate.SQL: ERROR
    root: INFO
spring:
  banner:
    location: classpath:banner.txt
  user:
    datasource:
      jdbcUrl: jdbc:mysql://mysql:3306/myspringapps?useSSL=false
      password: ENC(iV6xk0sOKde113G+RuSyK/n0Wnze7h2W1rNGgOEEm5VM+DRbPSG1O6WR3wa4RE13)
      username: spring
      driver-class-name: com.mysql.cj.jdbc.Driver
      hibernate:
        ddl-auto: update
        show-sql: true
        format-sql: true
jasypt:
  encryptor:
    password: rXzpBMH4EkKQMYAhalGMik8+Jz51Njb4OVYrSj8iIKSKrA==
server:
  port: 9090
api:
  backed:
    url: http://localhost:9191/api/v1/producer/getMessage
  admin:
    id: e1482313-aea9-4029-9214-505fce95e8bf
resilience4j:
  circuitbreaker:
    instances:
      serviceA:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      serviceA:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  ratelimiter:
    instances:
      serviceA:
        registerHealthIndicator: false
        limitForPeriod: 10
        limitRefreshPeriod: 10s
        timeoutDuration: 3s
springdoc:
  api-docs:
    path: /v3/api-docs.yaml
  swagger-ui:
    disable-swagger-default-url: true
